version: "3"

dotenv: ['.env']

tasks:
  init:
    cmd: cp .env.sample .env
    silent: true

  docker-run:
    cmd: docker-compose up -d
    silent: true

  migrate-up:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - echo "Running migrations..."
      - docker run --rm -v ./migrations:/migrations --network=host migrate/migrate -path=/migrations/ -database postgres://root:password@localhost:12000/pet_adoption_platform?sslmode=disable up
#    silent: true

  migrate-down:
    cmds:
      - echo "Rolling back migrations..."
      - docker-compose exec app php artisan migrate:rollback
    silent: true