version: "3"

dotenv: ['.env']

tasks:
  run:
    cmds:
      - |
        if [ -n "{{.CONFIG_PATH}}" ]; then
          go run cmd/url-shortener/main.go -config={{.CONFIG_PATH}}
        else
          go run cmd/url-shortener/main.go
        fi
    silent: true